spring:
  application:
    version: '@project.version@'
    name: support-test
  h2:
    console:
      path: /h2-console
      enabled: true
server:
  port: 0
  contextPath: /test
  address: localhost
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
tenant:
  database:
    available: TEST
    default: TEST
  environment:
    available: ENV1, ENV2, ENV3
    default: ENV1
database:
  default:
    driver-class-name: org.h2.Driver
  default-connections:
    - database: TEST
      username: sa
      password: ""
      schema: TEST
  environments:
    - environment: ENV1
      connections:
        - database: TEST
          url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=Oracle
    - environment: ENV2
      connections:
        - database: TEST
          url: jdbc:h2:mem:local;DB_CLOSE_DELAY=-1;MODE=Oracle
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  show_sql: true
  cache:
    use_second_level_cache: false
    use_query_cache: false
test:
  logins:
    - environment: ENV1
      names: doms836
    - environment: ENV2
      names: doms935, marmar702
    - environment: ENV3
      names: domslu560
security:
  permissions:
    - environment: ENV1
      permission-names: TEST_MODULE, TEST_MODULE_TWO
    - environment: ENV2
      permission-names: TEST_MODULE
    - environment: ENV3
      permission-names:
ssh:
  default:
    port: 22
    password: appuser
    user: appuser
  connections:
    - environment: ENV1
      user: user
      ip: 127.0.0.1
      password: pass
    - environment: ENV2
      ip: 127.0.0.2