spring:
  application:
    name: support-context
server:
  port: 0
  contextPath: /context
  address: localhost
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
tenant:
  database:
    any: true
    default: TEST
  environment:
    any: true
    default: ENV1
context:
  services: support-test, support-sql-executor