server:
  port: 8074
  address: 127.0.0.1
spring:
  application:
    name: support-apigateway
eureka:
  client:
    fetchRegistry: true
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
zuul:
  prefix: /work-support
  routes:
    sql-executor-service:
      path: /sql-executor/**
      serviceId: support-sql-executor
    script-executor-service:
      path: /script-executor/**
      serviceId: support-script-executor
    log-downloader-service:
      path: /log-downloader/**
      serviceId: support-log-downloader
    context-service:
      path: /context/**
      serviceId: support-context